//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDB2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.OrderProes = new HashSet<OrderPro>();
        }

        [Display(Name = "ID Khách hàng")]
        [Required(ErrorMessage = "ID not empty ...")]
        public int IDCus { get; set; }


        [Display(Name = "Họ và tên")]
        [Required(ErrorMessage = "Name not empty ...")]
        public string NameCus { get; set; }


        [Display(Name = "Số điện thoại")]
        [Required(ErrorMessage = "Phone not empty ...")]
        public string PhoneCus { get; set; }


        [Display(Name = "Email")]
        [Required(ErrorMessage = "Email not empty ...")]
        public string EmailCus { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPro> OrderProes { get; set; }
    }
}
